# Generated by Django 4.2.1 on 2023-05-12 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_rename_expiration_data_creditcard_expiration_date_and_more'),
        ('carritos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carritos.cart')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.creditcard')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile')),
            ],
        ),
    ]
